### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by giodamelio** [abaldwin88/roamer#15]
It would be great if there was some sort of confirmation flag, where it would output the commands it was going to run, but ask for a `y/n` before actually running anything.

**Comment by alex-bender** [comment]
Hi @abaldwin88! I'm gonna take this issue and I have question.
Should I add argument `--force-yes` or so to not to ask user? Just to be noninteractive.

**Comment by alex-bender** [comment]
You can check this commit: https://github.com/alex-bender/roamer/commit/30831ebeceefd368a60555f615ad516ac7c9c693  
And of course it'll break all tests.
So I need your advice, how it would better to implement argument handling.

**Comment by alex-bender** [comment]
As far as I understand we can pass arguments to the session instance and then check this flag in the `process` func. What do you think @abaldwin88 ?

**Comment by vimeitor** [comment]
You are not going to change the default behavior of not asking the commands to run, will you?

**Comment by alex-bender** [comment]
I think that it is what's asked here. To ask user before action. So probably It would be default behavior.
But anyway -- It's up to owner to decide.

**Comment by alex-bender** [comment]
Here is the code with `--skipapproval` flag:
https://github.com/abaldwin88/roamer/compare/master...alex-bender:confirmation

**Comment by vimeitor** [comment]
Thinking about it, it might be a good idea. I think I would be fine with this being default behavior.

**Comment by alex-bender** [comment]
@vimeitor anyway, you can do `alias roamer=roamer --skipapproval`. Do not forget that!

**Comment by giodamelio** [comment]
@alex-bender That's exactly what I was looking for.  Been using your code for the last few hours to refactor some stuff and it's working great.

**Comment by alex-bender** [comment]
@giodamelio Feel free to comment out here: https://github.com/alex-bender/roamer/commit/0071168d881b8e828fa303e6699d8b68521f33f2 anything you consider important.

**Comment by giodamelio** [comment]
I did just notice that it asks for confirmation even if you don't make any changes. It's probably ok to print a message and exit in that case.

**Comment by alex-bender** [comment]
Yeah, this is the one annoying thing what I want to remove.

**Comment by abaldwin88** [comment]
I went back and forth on what should be the default here.  Ultimately I think it's best that the safest option be the default.  We should however include a short note in the prompt to nudge users in the right direction.  Something to the effect of "This can be skipped by passing --skip-approval"

One small thing I would ask is that the flag the user passes should be `--skip-approval` with the extra dash instead of `--skipapproval`

For fixing the tests you should just need to pass in the new flag here :  https://github.com/abaldwin88/roamer/blob/566760c4d4fa3c3d4b5084cb621011d620913244/tests/mock_session.py#L16
(Let me know if that doesn't get them working) 

I checked out your branch.  Looks like you're on the right path.  Looking forward to seeing the finished PR 👍

**Comment by alex-bender** [comment]
As about
> ..short note in the prompt..

personally I think that it isn't good idea, and it's better to put such things into the man pages or at least help (long version).
But let it be as you want it be.

**Comment by abaldwin88** [comment]
You can check `len(engine.commands) == 0`  to detect whether the user has made any changes that need to be processed.

My experience has been tools that require an extra prompt regularly will tell you how to skip it in the future.  e.g. `heroku pg:reset` for example will tell you about the `--confirm` flag.  Sure it's listed in the help but it makes it that much easier for newcomers.

**Comment by alex-bender** [comment]
> You can check

That's cool! Thanks.

As about flag -- do you want me to put the notice right after first line of the output? Or next to yes\no prompt? @abaldwin88

**Comment by abaldwin88** [comment]
Place it wherever you feel it would be least intrusive.  Appreciate your flexibility.

**Comment by alex-bender** [comment]
I've added notice about flag, but it's a `print` for now. Would you like to add logging support?

**Comment by alex-bender** [comment]
Here is a PR: https://github.com/abaldwin88/roamer/pull/28 Could you please review it?
