### ISSUE TITLE
not working with Pluma

### ISSUE THREAD

**Issue by nitrofurano** [abaldwin88/roamer#21]
Bug Report Template
## Steps to reproduce (start with removing ~/.roamer-data):
export ROAMER_EDITOR=pluma
run roamer on whatever directory
nothing happens

**Comment by nitrofurano** [comment]
question: on which text editors roamer were tested?

**Comment by abaldwin88** [comment]
The editor needs the option to block or run in the foreground.  pluma does not support this...
https://github.com/mate-desktop/pluma/issues/212

It's only been tested on vim/nano/neovim/emacs.  I am aware there are issues for atom, sublime and textmate even when using the proper flags.  The fix should be easy to put in for those editors but I haven't had a chance yet.  This library blew up in popularity faster than anticipated.

**Comment by abaldwin88** [comment]
I'll expand what is needed for your text editor to work in the FAQ section.  The editor has to be capable of writing out messages when using `git commit`
