### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by alex-bender** [abaldwin88/roamer#25]
Hello, I'd like to contribute.
How can I help?

**Comment by abaldwin88** [comment]
Awesome!

Roamer is a young project so I am hopeful that will make it easy for people to dig in and contribute.  The popularity of this repo really blew up faster than anticipated.  I've got a lot of things I want to get done and only so much free time.

These are pretty easy pickings:

* https://github.com/abaldwin88/roamer/issues/15
* https://github.com/abaldwin88/roamer/issues/12
* https://github.com/abaldwin88/roamer/issues/12

Here's how to do a developer install  (I'm adding this to the contributing doc):

```
# fork it on github
cd ~
git clone https://github.com/YOUR_USER_NAME/roamer.git
cd roamer
sudo pip install -e .
```

Make sure you at least have pylint installed ( `pip install pylint` ) so you can validate your build before the PR.  If you have trouble getting tox rolling, just test against your local python version and let travis run tox when you submit the PR.

```
pylint roamer tests
python -m unittest discover
```

P.S.

If you happen to be a vimscript wizard I could really use some help:
* https://github.com/abaldwin88/roamer.vim/issues/1

**Comment by alex-bender** [comment]
That's great! Thanks for introducing. I'll pick up something (you've duplicated #12 in your list).
Also I have couple ideas to improve, but I'll better raise awareness for a while.
And I'm a vim user, but vimscript is not my strong site, but I can try. (It gonna be slow).
btw -- It could be great to have at least couple lines about roamer.vim at Readme file.
