### ISSUE TITLE
Cannot swap two files

### ISSUE THREAD

**Issue by antoine-atmire** [abaldwin88/roamer#26]
Bug Report Template

## roamer --version: 
0.2.1
## OS: 
mac os x 10.11.6
## Python version: 
2.7.10
## Steps to reproduce (start with removing ~/.roamer-data):

```
$ mkdir test
$ cd test
$ echo "file1" > file1
$ echo "file2" > file2
$ roamer
```

I want to rename file1 -> file2 and file2 -> file1, so  I swap the two hashes (or the two file names, the same happens)
before editing:
```
" pwd: /private/tmp/test
file2 | fb4274b4ca38
file1 | c5075497aa5f
```
after editing:
```
" pwd: /private/tmp/test
file2 | c5075497aa5f
file1 | fb4274b4ca38
```

save, quit and inspect the result
```
$ roamer
roamer-trash-copy /private/tmp/test/file2
roamer-trash-copy /private/tmp/test/file1
cp /private/tmp/test/file2 /private/tmp/test/file1
cp /private/tmp/test/file1 /private/tmp/test/file2
$ cat file1
file2
$ cat file2
file2
```

Both files now have "file2" as content.

**Comment by abaldwin88** [comment]
Excellent bug report 👍
