### ISSUE TITLE
.roamerrc

### ISSUE THREAD

**Issue by alex-bender** [abaldwin88/roamer#30]
Hi Alex, what do you think about adding `.roamerrc` file to keep some options there?

**Comment by abaldwin88** [comment]
@alex-bender Yes that would be ideal 👍   There is an open issue to do so: 
 https://github.com/abaldwin88/roamer/issues/2

**Comment by alex-bender** [comment]
Right. I've saw that. I'd like to add it. Will raise PR wen will be ready. Do you have any specific desires?

**Comment by abaldwin88** [comment]
Yep I'll post in the other thread so others will have a chance to comment.  Also feel free to email me directly using the address listed in the git repo.
