### ISSUE TITLE
Hash collisions should cause failure

### ISSUE THREAD

**Issue by abaldwin88** [abaldwin88/roamer#4]

**Comment by alex-bender** [comment]
@abaldwin88 
Hello Alex, I've created little tool, which helped me find one bug. Please check it out here: https://github.com/alex-bender/roamer_collisions

**Comment by alex-bender** [comment]
I was reviewing whole project and noticed only now that hash is 12 for now. I will test with it later.

**Comment by alex-bender** [comment]
Also, what do you think about including file size to the hash calculation? It will fix that .git folder issue.

**Comment by abaldwin88** [comment]
@alex-bender That's a great tool!  I just arbitrarily picked 12 for the hash length.  This tool should help us pick a logical cutoff length.  It may also prove that we should give users the option to manually set the hash length.

One thing I noticed was that the hash calculation in your tool needs an adjustment to match roamer.  Roamer uses the full path where as you are just using the filename.

I changed both `hash_seed` assignments to use `abs_path`...
```
hash_seed = abs_path + str(os.path.getmtime(abs_path))
```

I started running `time ./findit.py ~/` but my home directory is massive so it looks like it might take awhile.  I'm going to let it run overnight and report back the results.  I'd be curious to hear the results for your home directory after making the above modification.

**Comment by alex-bender** [comment]
I've changed length to 12 and `hash_seed` is calculating based on `abs_path` now.
I'm gonna make it more informative by adding file counters.
I can inform you about new commits if you want.

**Comment by alex-bender** [comment]
@abaldwin88 Now I didn't think that it's a great tool. I've changed the length to 12 and `hash_seed` assignments to `abs_path` and ran it overnight (unfortunately without `time`) so here is the results:
```
python3 findit.py /home/
Visited items: 880674
Hash, count
7b12bc7f79f3 1
2abc40865a50 1
957fdd8e9488 1
25ab779df9f2 1
0fc6cff4960b 1
61fdaa9e5f67 1
681e5c8d267e 1
ea52a1cfad14 1
77f3f3cc343f 1
71a3797932bf 1
```
Seems that it was work in vain.

**Comment by abaldwin88** [comment]
I certainly wouldn't call it work in vain.  It was a good pragmatic test for a potential issue.  Here are my results...

```
Visited items: 2949460
Hash, count
35d6be85ef1d 2
c132d1f58b0c 1
223c107643a9 1
d3719fc18d2a 1
56780739e35c 1
625a2f9db994 1
9fc7e35e17ad 1
e3bd67cd5752 1
985f245e8d72 1
789400e7382b 1
    17835.82 real     17466.23 user       265.73 sys
```
